### ISSUE TITLE
Deploy Sockethub test instance and hal8000 to Hetzner box

### ISSUE THREAD

**Issue by skddc** [67P/meta#5]
We recently got some cheap metal at hetzner.de in order to install a full Bitcoin node etc. for Counterwallet.

@bumi I'm not sure if we're using any of that for real currently. I'd like to upgrade the box to Ubuntu 15.04 with a clean install, so we can use systemd for running the node.js apps as well as anything else we need from the start. It's already available via their control panel, so I'm wondering if I should wipe the box or not. Just let me know, so I can either flip the switch or not.

**Comment by gregkare** [comment]
This should have been closed a while ago

**Comment by raucao** [comment]
Where can we find information about the running Sockethub instance?

**Comment by gregkare** [comment]
@skddc I've added a README to the cookbook: https://gitlab.com/kosmos/chef/blob/1bb9a44ac4c75fb31dd7f71a56bd92be1b64cdf3/site-cookbooks/sockethub/README.md

**Comment by raucao** [comment]
Great!

Would actually be cool to put that in the Chef Supermarket at some point in the future (when it's more stable).
